/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GradeAverageRouteImport } from './routes/grade-average'
import { Route as GradeCalculatorRouteImport } from './routes/grade-calculator'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GradeAverageRoute = GradeAverageRouteImport.update({
  id: '/grade-average',
  path: '/grade-average',
  getParentRoute: () => rootRouteImport,
} as any)
const GradeCalculatorRoute = GradeCalculatorRouteImport.update({
  id: '/grade-calculator',
  path: '/grade-calculator',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/grade-average': typeof GradeAverageRoute
  '/grade-calculator': typeof GradeCalculatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/grade-average': typeof GradeAverageRoute
  '/grade-calculator': typeof GradeCalculatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/grade-average': typeof GradeAverageRoute
  '/grade-calculator': typeof GradeCalculatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/grade-average' | '/grade-calculator'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/grade-average' | '/grade-calculator'
  id: '__root__' | '/' | '/grade-average' | '/grade-calculator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GradeAverageRoute: typeof GradeAverageRoute
  GradeCalculatorRoute: typeof GradeCalculatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grade-average': {
      id: '/grade-average'
      path: '/grade-average'
      fullPath: '/grade-average'
      preLoaderRoute: typeof GradeAverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grade-calculator': {
      id: '/grade-calculator'
      path: '/grade-calculator'
      fullPath: '/grade-calculator'
      preLoaderRoute: typeof GradeCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GradeAverageRoute: GradeAverageRoute,
  GradeCalculatorRoute: GradeCalculatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
